/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as boards_mutation from "../boards/mutation.js";
import type * as boards_query from "../boards/query.js";
import type * as members_mutation from "../members/mutation.js";
import type * as members_query from "../members/query.js";
import type * as organization_mutation from "../organization/mutation.js";
import type * as organization_query from "../organization/query.js";
import type * as users_mutation from "../users/mutation.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "boards/mutation": typeof boards_mutation;
  "boards/query": typeof boards_query;
  "members/mutation": typeof members_mutation;
  "members/query": typeof members_query;
  "organization/mutation": typeof organization_mutation;
  "organization/query": typeof organization_query;
  "users/mutation": typeof users_mutation;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
