import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ConvexProviderWithClerkProvider from "@/lib/providers/ConvexProviderWithClerk";

const inter = Open_Sans({ preload: false, weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-300`}>
        <ConvexProviderWithClerkProvider>
          {children}
        </ConvexProviderWithClerkProvider>
      </body>
    </html>
  );
}
